In [12]:
from transformers import AutoModelForCausalLM, AutoTokenizer, GenerationConfig

model_test = AutoModelForCausalLM.from_pretrained('roneneldan/TinyStories-33M')
tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-neo-125M")
prompt = "Once upon a time there was"
input_ids = tokenizer.encode(prompt, return_tensors="pt")

# Generate completion
output = model_test.generate(input_ids, max_length = 1000, num_beams=1)

# Decode the completion
output_text = tokenizer.decode(output[0], skip_special_tokens=True)

# Print the generated text
print(output_text)
print(model_test)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.


Once upon a time there was a little girl named Lucy. She was three years old and loved to explore. One day, Lucy was walking in the park when she saw a big, red balloon. She was so excited and ran over to it.

"Can I have it?" she asked.

"No," said her mom. "It's too big for you. You can't have it."

Lucy was sad, but then she saw a small, red balloon. She smiled and said, "I want that one!"

Her mom smiled and said, "Okay, let's go get it."

So they went to the balloon and Lucy was so happy. She held the balloon tight and ran around the park with it. She laughed and smiled and had so much fun.

When it was time to go home, Lucy hugged the balloon and said, "I love you, balloon!"

Her mom smiled and said, "I love you too, Lucy."

GPTNeoForCausalLM(
  (transformer): GPTNeoModel(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(2048, 768)
    (drop): Dropout(p=0.0, inplace=False)
    (h): ModuleList(
      (0-3): 4 x GPTNeoBlock(
        (ln_1): LayerNorm((768,), eps=1e-05, element

In [ ]:
import torch
from torch import nn
import pytorch_lightning as pl
import torch.nn.functional as F

from transformer_lens import HookedTransformer, utils
MODEL_PATH='roneneldan/TinyStories-33M'
DEVICE='cuda'

model = HookedTransformer.from_pretrained_no_processing(
    MODEL_PATH,
    device=DEVICE,
    #dtype=torch.float16,
    default_padding_side='left',
    #fp16=True
)





/home/mm/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


Loaded pretrained model roneneldan/TinyStories-33M into HookedTransformer
HookedTransformer(
  (embed): Embed()
  (hook_embed): HookPoint()
  (pos_embed): PosEmbed()
  (hook_pos_embed): HookPoint()
  (blocks): ModuleList(
    (0-3): 4 x TransformerBlock(
      (ln1): LayerNorm(
        (hook_scale): HookPoint()
        (hook_normalized): HookPoint()
      )
      (ln2): LayerNorm(
        (hook_scale): HookPoint()
        (hook_normalized): HookPoint()
      )
      (attn): Attention(
        (hook_k): HookPoint()
        (hook_q): HookPoint()
        (hook_v): HookPoint()
        (hook_z): HookPoint()
        (hook_attn_scores): HookPoint()
        (hook_pattern): HookPoint()
        (hook_result): HookPoint()
      )
      (mlp): MLP(
        (hook_pre): HookPoint()
        (hook_post): HookPoint()
      )
      (hook_attn_in): HookPoint()
      (hook_q_input): HookPoint()
      (hook_k_input): HookPoint()
      (hook_v_input): HookPoint()
      (hook_mlp_in): HookPoint()
      (hook

TypeError: argument 'ids': 'list' object cannot be interpreted as an integer

In [14]:
print(model_cache)

# print(model_cache['blocks.0.mlp.hook_pre'])
# print(model_cache['blocks.0.mlp.hook_post'])
# print(model_cache['blocks.0.hook_mlp_out'])
print(model_cache['blocks.0.ln2.hook_normalized'].shape)
print(model_cache['blocks.0.mlp.hook_pre'].shape)
print(model_cache['blocks.0.mlp.hook_post'].shape)
print(model_cache['blocks.0.hook_mlp_out'].shape)
# logits, model_cache = model.run_with_cache(["There once was","Once upon a time there was"])
# print(logits.shape)

ActivationCache with keys ['hook_embed', 'hook_pos_embed', 'blocks.0.hook_resid_pre', 'blocks.0.ln1.hook_scale', 'blocks.0.ln1.hook_normalized', 'blocks.0.attn.hook_q', 'blocks.0.attn.hook_k', 'blocks.0.attn.hook_v', 'blocks.0.attn.hook_attn_scores', 'blocks.0.attn.hook_pattern', 'blocks.0.attn.hook_z', 'blocks.0.hook_attn_out', 'blocks.0.hook_resid_mid', 'blocks.0.ln2.hook_scale', 'blocks.0.ln2.hook_normalized', 'blocks.0.mlp.hook_pre', 'blocks.0.mlp.hook_post', 'blocks.0.hook_mlp_out', 'blocks.0.hook_resid_post', 'blocks.1.hook_resid_pre', 'blocks.1.ln1.hook_scale', 'blocks.1.ln1.hook_normalized', 'blocks.1.attn.hook_q', 'blocks.1.attn.hook_k', 'blocks.1.attn.hook_v', 'blocks.1.attn.hook_attn_scores', 'blocks.1.attn.hook_pattern', 'blocks.1.attn.hook_z', 'blocks.1.hook_attn_out', 'blocks.1.hook_resid_mid', 'blocks.1.ln2.hook_scale', 'blocks.1.ln2.hook_normalized', 'blocks.1.mlp.hook_pre', 'blocks.1.mlp.hook_post', 'blocks.1.hook_mlp_out', 'blocks.1.hook_resid_post', 'blocks.2.hook_re

In [41]:
#print(model)
logits, model_cache = model.run_with_cache("Once upon a time there was")
print(logits.shape)
print(logits)
pred=torch.argmax(logits, dim=2)
print(pred[0])
output_text = tokenizer.decode(pred[0], skip_special_tokens=True)
print(output_text)

torch.Size([1, 7, 50257])
tensor([[[ 6.3279,  9.3715, -2.1419,  ..., -4.3756, -1.5810, 13.7179],
         [ 5.7759,  4.9415,  0.5219,  ..., -6.6127, -1.7052, -0.1786],
         [ 3.6312,  4.2132, -2.8699,  ..., -5.8460, -1.8137,  5.7784],
         ...,
         [ 6.4051,  4.8736, -0.6806,  ..., -6.9789, -3.9006,  0.6788],
         [ 4.1072,  4.2895, -2.9451,  ..., -6.5386,  0.7935,  3.7805],
         [ 0.0465,  2.3845, -3.6768,  ..., -5.8280, -3.4649,  1.5353]]],
       device='cuda:0', grad_fn=<ViewBackward0>)
tensor([ 628, 2402,  257,  640,   11,  373,  257], device='cuda:0')


 upon a time, was a


In [42]:
prompt = "Once upon a time there was"
input_ids = tokenizer.encode(prompt, return_tensors="pt")
print(input_ids)
logits, model_cache = model.run_with_cache(input_ids, remove_batch_dim=True)
print(logits)
pred=torch.argmax(logits, dim=2)
print(pred[0])
output_text = tokenizer.decode(pred[0], skip_special_tokens=True)
print(output_text)
# print(logits.shape)
# print(type(model_cache))


tensor([[7454, 2402,  257,  640,  612,  373]])
tensor([[[ 3.9021,  3.4876, -0.6425,  ..., -6.2630, -0.1213,  2.9728],
         [ 0.6864,  1.7183, -5.3212,  ..., -5.7546, -2.9005,  3.0420],
         [ 0.6857, -0.0636, -5.0578,  ..., -6.9403, -2.8542,  1.0349],
         [ 6.7785,  3.1395, -1.3534,  ..., -6.7419, -2.7093, -0.7435],
         [ 4.6727,  3.2916, -3.0789,  ..., -6.5431,  0.9389,  2.6959],
         [ 1.0727,  1.5860, -3.7764,  ..., -5.9963, -3.0989,  1.0999]]],
       device='cuda:0', grad_fn=<ViewBackward0>)
tensor([2402,  257,  640,   11,  373,  257], device='cuda:0')
 upon a time, was a


In [52]:
model.eval()
prompt = "Once upon a time there was"
input_ids = tokenizer.encode(prompt, return_tensors="pt")
print(input_ids)
logits, model_cache = model.run_with_cache(input_ids, remove_batch_dim=True)
print(logits)
pred=torch.argmax(logits, dim=2)
print(pred[0])
output_text = tokenizer.decode(pred[0], skip_special_tokens=True)
print(output_text)

tensor([[7454, 2402,  257,  640,  612,  373]])
tensor([[[ 3.9021,  3.4876, -0.6425,  ..., -6.2630, -0.1213,  2.9728],
         [ 0.6864,  1.7183, -5.3212,  ..., -5.7546, -2.9005,  3.0420],
         [ 0.6857, -0.0636, -5.0578,  ..., -6.9403, -2.8542,  1.0349],
         [ 6.7785,  3.1395, -1.3534,  ..., -6.7419, -2.7093, -0.7435],
         [ 4.6727,  3.2916, -3.0789,  ..., -6.5431,  0.9389,  2.6959],
         [ 1.0727,  1.5860, -3.7764,  ..., -5.9963, -3.0989,  1.0999]]],
       device='cuda:0', grad_fn=<ViewBackward0>)
tensor([2402,  257,  640,   11,  373,  257], device='cuda:0')
 upon a time, was a


In [24]:
from datasets import load_dataset

ds = load_dataset("roneneldan/TinyStories",split='train')
print(type(ds))

<class 'datasets.arrow_dataset.Dataset'>


In [50]:
print(ds)
def tokenize(data):
    tokenizer.pad_token = tokenizer.eos_token
    return tokenizer(data['text'], return_tensors="pt",padding=True)
ds.set_transform(tokenize)

Dataset({
    features: ['text'],
    num_rows: 2119719
})


In [51]:
from torch.utils.data import DataLoader
train_loader=DataLoader(ds,batch_size=2,shuffle=True)
print(next(iter(train_loader)))
#print(model.run_with_cache(next(iter(train_loader))['text']))

{'input_ids': tensor([[31160,   290,  3932,   389,  2460,    13,  1119,   588,   284,   711,
           351, 14958,    13, 11735,   468,   257,  1263,  6614,    13,   632,
           460,  6129,   287,   262,  1633,    13,  3932,   468,   257,  1402,
          1097,    13,   632,   460,  3708,   319,   262,  2323,    13,   198,
           198,  3198,  1110,    11,   484,   467,   284,   262,  3952,   351,
           511, 34015,    13,  1119,   766,   257,  1263, 12788,    13, 11735,
          1139,    11,   366,  5756,   338,   467,   510,   262, 12788,   290,
          6129,   616,  6614,  2474,  3932,  1139,    11,   366, 11380,    11,
           326,  5238,  1257,  2474,   198,   198,  2990,  1057,   510,   262,
         12788,   351,   511, 14958,    13, 11735, 12542,   607,  6614,   287,
           262,  1633,    13,   632, 17607,  1029,   290,  1290,    13,  3932,
         16860,   290,   537,  1686,    13,   679,  1139,    11,   366, 22017,
            11,   534,  6614,   318,  

In [29]:
from torch.utils.data import DataLoader
train_loader=DataLoader(ds,batch_size=2,shuffle=True)
print(next(iter(train_loader)))
print(model.run_with_cache(next(iter(train_loader))['text']))

{'text': ['Once upon a time, a little girl named Lily went for a walk in the woods. She saw a frog and said, "Hello, frog! You look harmless. Can I pick you up?" The frog replied, "Yes, you can pick me up, but be careful. I might joke around with you."\n\nLily picked up the frog and they started to walk together. The frog said, "Do you want to hear a joke?" Lily giggled and said, "Yes, please!" The frog said, "Why did the frog call his insurance company? Because he had a jump in his car!" Lily laughed and said, "That\'s funny, frog!"\n\nThey kept walking and talking until they reached a pond. The frog said, "This is my home. Thank you for the fun walk, Lily." Lily said, "Thank you for the joke, frog. I had a great time!" And with that, Lily waved goodbye to the frog and went back home.', 'Once there was a little girl named Sarah. She was always smiling and full of life. Today Sarah was feeling extra special. She skipped around the garden picking flowers of all colors. \n\nWhen she was 

In [ ]:

cfg = {
    "seed": 49,
    #"batch_size": 4096,
    #"buffer_mult": 384,
    "lr": 1e-4,#1e-5
    #"num_tokens": int(2e9),
    "l1_coeff": 3e-4,
    #"beta1": 0.9,
    #"beta2": 0.99,
    "dict_mult": 16,
    "seq_len": 128,
    "d_emb": 2048,
    "enc_dtype":"fp32",
    #"remove_rare_dir": False,
}
# cfg["model_batch_size"] = 64
# cfg["buffer_size"] = cfg["batch_size"] * cfg["buffer_mult"]
# cfg["buffer_batches"] = cfg["buffer_size"] // cfg["seq_len"]


DTYPES = {"fp32": torch.float32, "fp16": torch.float16, "bf16": torch.bfloat16}
class AutoEncoder(nn.Module):
    def __init__(self, cfg):
        super().__init__()
        d_hidden = cfg["d_emb"] * cfg["dict_mult"]
        d_mlp = cfg["d_emb"]
        l1_coeff = cfg["l1_coeff"]
        dtype = DTYPES[cfg["enc_dtype"]]
        torch.manual_seed(cfg["seed"])
        self.W_enc = nn.Parameter(torch.nn.init.kaiming_uniform_(torch.empty(d_mlp, d_hidden, dtype=dtype)))
        self.W_dec = nn.Parameter(torch.nn.init.kaiming_uniform_(torch.empty(d_hidden, d_mlp, dtype=dtype)))
        self.b_enc = nn.Parameter(torch.zeros(d_hidden, dtype=dtype))
        self.b_dec = nn.Parameter(torch.zeros(d_mlp, dtype=dtype))

        self.W_dec.data[:] = self.W_dec / self.W_dec.norm(dim=-1, keepdim=True)

        self.d_hidden = d_hidden
        self.l1_coeff = l1_coeff

        #self.to("cuda")

    def forward(self, x):
        x_cent = x - self.b_dec
        acts = F.relu(x_cent @ self.W_enc + self.b_enc)
        x_reconstruct = acts @ self.W_dec + self.b_dec
        
        return x_reconstruct, acts

In [ ]:
class SparseTranscoder(pl.LightningModule):
    def __init__(self, config, hooked_transformer, layer, **kwargs):
        super().__init__(**kwargs)
        self.transcoder=AutoEncoder(cfg=config)
        self.llm=hooked_transformer
        self.layer=layer
        self.lr=config['lr']
        for param in self.transcoder.parameters():
            print(param)

    def forward(self, x):
        return self.transcoder(x)
    
    def training_step(self, batch, batch_idx):
        # for now we sample the llm during training - in the future maybe caching activations will prove usefull
        with torch.no_grad():
            logits, model_cache = self.llm.run_with_cache(batch)

        if type(self.layer)==int:
            input_acts=model_cache[f'blocks.{self.layer}.ln2.hook_normalized']
            output_acts=model_cache[f'blocks.{self.layer}.hook_mlp_out']
        else:
            raise NotImplementedError()
        
        preds, acts=self.forward(input_acts)

        l2_loss = (preds.float() - output_acts.float()).pow(2).sum(-1).mean(0)
        l1_loss = self.transcoder.l1_coeff * (acts.float().abs().sum())
        loss = l2_loss + l1_loss
        self.log('train_loss', loss)
        self.log('reconstruction_loss', l2_loss)
        self.log('sparsity_loss',l1_loss)
        return loss
    
    def validation_step(self, batch, batch_idx):
        # for now we sample the llm during training - in the future maybe caching activations will prove usefull
        with torch.no_grad():
            logits, model_cache = self.llm.run_with_cache(batch)

        if type(self.layer)==int:
            input_acts=model_cache[f'blocks.{self.layer}.ln2.hook_normalized']
            output_acts=model_cache[f'blocks.{self.layer}.hook_mlp_out']
        else:
            raise NotImplementedError()
        
        preds, acts=self.forward(input_acts)

        l2_loss = (preds.float() - output_acts.float()).pow(2).sum(-1).mean(0)
        l1_loss = self.transcoder.l1_coeff * (acts.float().abs().sum())
        loss = l2_loss + l1_loss
        self.log('val_loss', loss)
        # self.log('reconstruction_loss', l2_loss)
        # self.log('sparsity_loss',l1_loss)
        return loss
    
    def configure_optimizers(self):
        return torch.optim.Adam(self.transcoder.parameters(), lr=self.lr)
    


In [22]:
test=SparseTranscoder(cfg,model,0)

Parameter containing:
tensor([[-0.0123, -0.0060, -0.0068,  ...,  0.0070, -0.0119,  0.0022],
        [-0.0106,  0.0090,  0.0062,  ...,  0.0114,  0.0029, -0.0124],
        [ 0.0021,  0.0134,  0.0048,  ..., -0.0102, -0.0104, -0.0030],
        ...,
        [ 0.0094, -0.0122, -0.0112,  ...,  0.0038,  0.0104,  0.0067],
        [-0.0026,  0.0015, -0.0058,  ..., -0.0104,  0.0046,  0.0033],
        [-0.0032, -0.0122, -0.0110,  ...,  0.0037, -0.0103, -0.0076]],
       requires_grad=True)
Parameter containing:
tensor([[-0.0008,  0.0127, -0.0287,  ...,  0.0242, -0.0174,  0.0071],
        [-0.0171, -0.0345, -0.0381,  ..., -0.0180,  0.0182, -0.0335],
        [ 0.0236,  0.0016, -0.0086,  ..., -0.0343, -0.0184, -0.0095],
        ...,
        [ 0.0138, -0.0150,  0.0128,  ...,  0.0238, -0.0327, -0.0351],
        [-0.0310, -0.0018, -0.0158,  ..., -0.0052,  0.0241, -0.0364],
        [-0.0230,  0.0170,  0.0040,  ...,  0.0262,  0.0070, -0.0219]],
       requires_grad=True)
Parameter containing:
tensor([0., 